### ISSUE TITLE
좋은 소스 공유해주셔서 감사합니다.

### ISSUE THREAD

**Issue by stonetiger84-ai** [eagle705/pytorch-bert-crf-ner#1]
해당 소스를 참조하여 사용하겠습니다.

**Comment by eagle705** [comment]
넵~! 궁금하신 사항있으시면 문의주시면 감사하겠습니다 :)

**Comment by tkwoo** [comment]
모두콘에서 발표 잘 들었습니다.
의미 있고 좋은 프로젝트라고 생각해요. 공유해주셔서 감사합니다.
