### ISSUE TITLE
기존의 PER, LOC과 같은 태그 외에 더 추가할 수 있는 방법이 있나요?

### ISSUE THREAD

**Issue by kwangrok92** [eagle705/pytorch-bert-crf-ner#8]
./data_in/NER-master/말뭉치-형태소_개체명 폴더에 임의의 txt 파일을
예를 들어
고라파덕    고라파덕    NNP    B-CHA
과 같이 수정해서 학습시켰는데 KeyError: 'B-CHA' 가 납니다.
혹시 태그를 추가하는 방법이 있을까요?

**Comment by dgks0n** [comment]
@kwangrok92 Did you change the configuration and added those tag in the list?

**Comment by kwangrok92** [comment]
I didn't modify config separately.
Can you tell me which file I need to modify?

**Comment by eagle705** [comment]
늦었지만 답변드립니다
https://github.com/eagle705/pytorch-bert-crf-ner/blob/master/experiments/base_model_with_crf_val/ner_to_index.json

해당 파일도 수정해보시면 될 것 같습니다

**Comment by kwangrok92** [comment]
답변 감사합니다! 

이걸 리눅스 가상서버에서 돌려보려고 합니다.
Ubuntu 18.04 LTS
conda 가상환경
![image](https://user-images.githubusercontent.com/36951242/94383693-c3a66800-017b-11eb-9876-6dd476578659.png)
![image](https://user-images.githubusercontent.com/36951242/94383715-cef99380-017b-11eb-90c5-4a580a08922f.png)
CUDA 9.2 (conda install pytorch==1.2.0 torchvision==0.4.0 cudatoolkit=9.2 -c pytorch)

이렇게 환경 만들어주고 python inference.py 돌려봤더니
![image](https://user-images.githubusercontent.com/36951242/94383903-4cbd9f00-017c-11eb-9e79-db51fe074c63.png)
위와 같은 에러가 납니다.

혹시 원인을 알 수 있을까요. 텐서플로우 버전 다운그레이드하라고 하는데
해당 프로젝트에서 tensorboard-plugin-wit 이외에 텐서플로우 모듈 자체를 사용하지 않고 있다고 나오네요.
